CREATE TABLE event (
  id BIGSERIAL NOT NULL PRIMARY KEY,
  score BIGINT NOT NULL,
  name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TYPE status AS ENUM ('pending', 'ok', 'reject');
CREATE TABLE achievement (
  id BIGSERIAL NOT NULL PRIMARY KEY,
  event_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  status status NOT NULL DEFAULT 'pending',
  file VARCHAR (32) NOT NULL
);

CREATE TYPE user_status AS ENUM ('user', 'admin');
CREATE TABLE account (
  id BIGSERIAL NOT NULL PRIMARY KEY,
  first_name VARCHAR (50) NOT NULL,
  second_name VARCHAR (50) NOT NULL,
  type user_status NOT NULL,
  email VARCHAR (50) NOT NULL UNIQUE,
  password VARCHAR (64) NOT NULL,
  score BIGINT NOT NULL DEFAULT 0,
  school_id BIGINT NOT NULL
);

CREATE TABLE password (
  user_id BIGINT NOT NULL,
  password VARCHAR (64) NOT NULL,
  date TIMESTAMP NOT NULL
);

CREATE TABLE school (
  id BIGSERIAL NOT NULL PRIMARY KEY,
  name VARCHAR (50) NOT NULL UNIQUE,
  city_id BIGINT NOT NULL,
  admin_id BIGINT NOT NULL DEFAULT 0,
  score BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE city (
  id BIGSERIAL NOT NULL PRIMARY KEY,
  name VARCHAR (50) NOT NULL UNIQUE
);